### PR TITLE
Fix Home/End keys

### PR DESCRIPTION
**Pull request by Belphemur**
Add support for CTRL+ARROW

### CODE REVIEW

**Comment by ThiefMaster** [comment]
Can you check if it also works fine inside tmux? My current config works fine there, but I also noticed these keys not working outside tmux - never could be bothered fixing it though, so thanks for the PR!

**Comment by ThiefMaster** [comment]
Actually... I wonder why the terminfo-based keys don't work. Wanna investigate? Maybe I'm using the wrong ones and there are other entries that do the job better?

**Comment by Belphemur** [comment]
To be honest, I don't know why the terminfo-based keys don't work. I checked online and it should work.
I'm using Tilix as terminal emulator, it's a vte based. That might be why.

This shouldn't change the behaviour of Tmux.

**Comment by ThiefMaster** [comment]
What's your `$TERM`?

**Comment by Belphemur** [comment]
xterm-256color

**Comment by ThiefMaster** [comment]
just realized the windows 10 terminal needs the same changes and i had them on my laptop. i amended your PR a bit to use the correct movement utils and added the missing binds for the alt-left/alt-right options

**Pull request merged**
